.PHONY: clean All

All:
	@echo "==========Building project:[ 20_1_FunctionTemplates_240 - Debug ]----------"
	@cd "C:\ANY\31_CPP\cpp-learning-beginner-to-beyond\Section20_STL\FunctionTemplates" && "$(MAKE)" -f  "20_1_FunctionTemplates_240.mk"
clean:
	@echo "==========Cleaning project:[ 20_1_FunctionTemplates_240 - Debug ]----------"
	@cd "C:\ANY\31_CPP\cpp-learning-beginner-to-beyond\Section20_STL\FunctionTemplates" && "$(MAKE)" -f  "20_1_FunctionTemplates_240.mk" clean
