.PHONY: clean All

All:
	@echo "==========Building project:[ Challenge_1_Solution - Debug ]----------"
	@cd "C:\ANY\31_CPP\cpp-learning-beginner-to-beyond\Section20_STL\Challenge_1_Solution" && "$(MAKE)" -f  "Challenge_1_Solution.mk"
clean:
	@echo "==========Cleaning project:[ Challenge_1_Solution - Debug ]----------"
	@cd "C:\ANY\31_CPP\cpp-learning-beginner-to-beyond\Section20_STL\Challenge_1_Solution" && "$(MAKE)" -f  "Challenge_1_Solution.mk" clean
