.PHONY: clean All

All:
	@echo "==========Building project:[ 20_17_ContainerAdaptors_PriorityQueue_264 - Debug ]=========="
	@cd "20_17_ContainerAdaptors_PriorityQueue_264" && "$(MAKE)" -f  "20_17_ContainerAdaptors_PriorityQueue_264.mk"
clean:
	@echo "==========Cleaning project:[ 20_17_ContainerAdaptors_PriorityQueue_264 - Debug ]----------"
	@cd "20_17_ContainerAdaptors_PriorityQueue_264" && "$(MAKE)" -f  "20_17_ContainerAdaptors_PriorityQueue_264.mk" clean
