.PHONY: clean All

All:
	@echo "==========Building project:[ 16_10_ChallengeSolution_Final - Debug ]=========="
	@cd "16_10_ChallengeSolution_Final" && "$(MAKE)" -f  "16_10_ChallengeSolution_Final.mk"
clean:
	@echo "==========Cleaning project:[ 16_10_ChallengeSolution_Final - Debug ]----------"
	@cd "16_10_ChallengeSolution_Final" && "$(MAKE)" -f  "16_10_ChallengeSolution_Final.mk" clean
