.PHONY: clean All

All:
	@echo "==========Building project:[ 18_9_Challenge - Debug ]=========="
	@cd "18_9_Challenge" && "$(MAKE)" -f  "18_9_Challenge.mk"
clean:
	@echo "==========Cleaning project:[ 18_9_Challenge - Debug ]----------"
	@cd "18_9_Challenge" && "$(MAKE)" -f  "18_9_Challenge.mk" clean
