.PHONY: clean All

All:
	@echo "==========Building project:[ 17_5_Challenge_204 - Debug ]=========="
	@cd "17_5_Challenge_204" && "$(MAKE)" -f  "17_5_Challenge_204.mk"
clean:
	@echo "==========Cleaning project:[ 17_5_Challenge_204 - Debug ]----------"
	@cd "17_5_Challenge_204" && "$(MAKE)" -f  "17_5_Challenge_204.mk" clean
